---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(p8105.datasets)
library(rnoaa)
library(plotly)
library(htmlwidgets)
library(tidyverse)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), # temperature min and max
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate( # change names of variables in id column.
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

Column {data-width=550}
-----------------------------------------------------------------------

### scatterplot: Relationships between Temp change and the Lowest Temp

```{r}
weather_df %>% 
  mutate(tchange = tmax - tmin) %>% 
  plot_ly(
    x = ~tchange, y = ~tmin, color = ~name,
    alpha = .5, type = "scatter", mode = "markers", colors = "viridis") %>% 
  layout(
    xaxis = list(title = "Temperature change (C)"),
    yaxis = list(title = "Lowest Temperature (C)"),
    title = "Relationships between Temp change and the Lowest Temp"
  )
```

Column {data-width=450}
-----------------------------------------------------------------------

### boxplot: Lowest Temperature of Locations

```{r}
weather_df %>% 
  mutate(
    name = factor(name),
    name = forcats::fct_relevel(name, c("Waikiki_HA"))) %>% 
  plot_ly(
    x = ~name, y = ~tmin, color = ~name,
    type = "box", colors = "viridis") %>% 
  layout(
    xaxis = list(title = "Locations"),
    yaxis = list(title = "Lowest Temperature (C)"),
    title = "Lowest Temp of Locations"
  )
```

### bar plot: Mean Precipitation per Month

```{r}
weather_df %>% 
  separate(date, into = c("year", "month", "day")) %>% 
  group_by(year, month, name) %>% 
  summarise(prcp_mean = mean(prcp)) %>% 
  mutate(prcp_mean = prcp_mean/10) %>% 
  plot_ly(
    x = ~month, 
    y = ~prcp_mean, color = ~name,
    type = "bar", colors = "viridis"
  ) %>% 
   layout(
    xaxis = list(title = "Month"),
    yaxis = list(title = "Mean Precipitation (mm)"),
    title = "Mean Precipitation per Month"
  )
```

