---
title: "Plotly examples"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Loading data

We're gonna look at NYC Airbnb data. 

```{r}
library(dplyr)
library(p8105.datasets)
library(rnoaa)
library(plotly)
library(htmlwidgets)
library(tidyverse)
```


```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), # temperature min and max
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate( # change names of variables in id column.
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

weather_df
```


# Plotly plots

## scatterplot

```{r}
weather_df %>% 
  mutate(tchange = tmax - tmin) %>% 
  plot_ly(
    x = ~tchange, y = ~tmin, color = ~name,
    alpha = .5, type = "scatter", mode = "markers", colors = "viridis") %>% 
  layout(
    xaxis = list(title = "Temperature change (C)"),
    yaxis = list(title = "Lowest Temperature (C)"),
    title = "Relationships between Temp change and the Lowest Temp"
  )
```

## boxplot

```{r}
weather_df %>% 
  mutate(
    name = factor(name),
    name = forcats::fct_relevel(name, c("Waikiki_HA"))) %>% 
  plot_ly(
    x = ~name, y = ~tmin, color = ~name,
    type = "box", colors = "viridis") %>% 
  layout(
    xaxis = list(title = "Locations"),
    yaxis = list(title = "Lowest Temperature (C)"),
    title = "Lowest Temp of Locations"
  )
```

## bar plot

```{r}
weather_df %>% 
  
  plot_ly(
    x = ~prcp, y = ~n, color = ~name,
    type = "bar", colors = "viridis"
  )
```





